project_id = "qplyvfyfqelmbvwzziec"

[functions.send-sms]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.create-admin]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.admin-create-booking]
verify_jwt = false

[functions.sms-webhook]
verify_jwt = false

[functions.register-webhook]
verify_jwt = false
